version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    env_file:
      - infra/postgres/.env
    volumes:
      - postgres-data:/data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U auth_user -d auth_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  auth-api:
    build:
      context: .
      target: production
    env_file:
      - ./envs/.env.docker
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - auth-api

volumes:
  postgres-data:
  redis-data:
